### ISSUE TITLE
CopyZipsFunction : An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied

### ISSUE THREAD

**Issue by gmarchand** [aws-quickstart/quickstart-cloud9-ide#30]
The cloudformation template can not be deployed with this configuration 

I use this cloudformation template `Cloud9 + QuickStart VPC (qs-1pb4pob92) (Please do not remove) May,29,2019` in eu-west-1

with these parameters : 
- OutputBucketName : gma-test
- QSS3BucketName : gma-test
- QSS3KeyPrefix : quickstart-cloud9-ide/
- BootstrapScriptS3Uri : s3://gma-test/bootstrap.sh

gma-test is a private S3 bucket

I have this error
```

[ERROR] 2020-02-20T16:02:58.532Z  Exception: An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied Traceback (most recent call last): File "/var/task/index.py", line 51, in handler copy_objects(source_bucket, dest_bucket, prefix, objects) File "/var/task/index.py", line 20, in copy_objects Key=key) File "/var/runtime/botocore/client.py", line 272, in _api_call return self._make_api_call(operation_name, kwargs) File "/var/runtime/botocore/client.py", line 576, in _make_api_call raise error_class(parsed_response, operation_name) botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied
@message
[ERROR] 2020-02-20T16:02:58.532Z 8c6fefde-cdfa-43ea-b5ea-faa8416f3734 Exception: An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied
Traceback (most recent call last):
File "/var/task/index.py", line 51, in handler
copy_objects(source_bucket, dest_bucket, prefix, objects)
File "/var/task/index.py", line 20, in copy_objects
Key=key)
File "/var/runtime/botocore/client.py", line 272, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/runtime/botocore/client.py", line 576, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied
```

**Comment by gmarchand** [comment]
Another log 
````
@log
xxx:/aws/lambda/AWS-Cloud9-IDE-summitparis-CopyZipsFunction-1LM724V0S8ADL
@message
copy_source: {'Bucket': 'gma-test', 'Key': 'quickstart-cloud9-ide/functions/packages/c9bootstrap/lambda.zip'}

Bucket
gma-test
Key
quickstart-cloud9-ide/functions/packages/c9bootstrap/lambda.zip
```

**Comment by gmarchand** [comment]
misuse

**Comment by bn-bnelson** [comment]
This error occurred for me as well.
